# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_sick',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
